# # Download and install Istio
# curl -L https://istio.io/download | ISTIO_VERSION=1.12.2 sh -
# cd istio-1.12.2

# # Install Istio to your cluster
# istioctl install --set profile=default
-----------------------------------------------------------------

# Label the namespace where you want to deploy the microservices
# kubectl label namespace default istio-injection=enabled

# # Deploy Istio components
# kubectl apply -f manifests/profiles/default.yaml
---------------------------------------------------------------

# istio-gateway.yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: microservices-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - "*"
    port:
      number: 80
      name: http
      protocol: HTTP

---

# istio-virtualservice.yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: microservices
spec:
  hosts:
  - "*"
  gateways:
  - microservices-gateway
  http:
  - route:
    - destination:
        host: cart-service.default.svc.cluster.local
        port:
          number: 8080
-------------------------

# kubectl apply -f istio-gateway.yaml
# kubectl apply -f istio-virtualservice.yaml

# kubectl get pods -n istio-system


