# shipping-service-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shipping-service
  template:
    metadata:
      labels:
        app: shipping-service
    spec:
      containers:
      - name: shipping-service
        image: jyothihomedocker/shipping-microservice:latest
        ports:
        - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: shipping-service
spec:
  selector:
    app: shipping-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
